version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ProgrammerDb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql 
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql  
      PMA_PORT: 3306   
   
   
       
     

  evoltis-technical-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evoltis-technical-be
    ports:
      - "5000:80"
    depends_on:
      - mysql

volumes:
  db-data:
